// Generated by Scripts/fandom-audit/audit.py — do not hand-edit.
//
// Fandom tags whose text after the dash is part of the real title, not a
// disambiguator. No syntactic rule can tell the two apart (see
// discussions/fandom-name-disambiguation.md), so these were classified
// offline by several AI agents with web search and are shipped as data.
//
// 32 entries, matched against the name `split` actually receives:
// the last '|' segment of the tag, not the whole multilingual tag.

enum FandomDisplayExceptions {
    /// Tags to render whole, with no part of the name demoted.
    static let keepWhole: Set<String> = [
        "15 - Meisetsu Kougyou Koukou Rugby Bu",
        "Aokana - Four Rhythms Across the Blue",
        "C.A.T. - Confidential Assassination Troop",
        "Cat Game - The Cat Collector! (Mino Games Video Game)",
        "Coil - A Circle of Children",
        "Cornetto \"40 - love\" Commercial",
        "Dancouga - Super Beast Machine God",
        "Daniel - The Wizard (Movie 2004)",
        "Dio - Distraught Overlord",
        "Dracula vs. Frankenstein - Duell der Giganten (Audio Drama)",
        "Dragon Age: Origins - Awakening",
        "Emma - A Victorian Romance",
        "Ich bin ein Star - Holt mich hier raus! (Germany TV)",
        "InuYasha - A Feudal Fairy Tale",
        "K11 - Kommissare im Einsatz",
        "Knights of the Old Republic II - The Sith Lords",
        "Looney Tunes - World of Mayhem",
        "MÄR - Märchen Awakens Romance",
        "Nothingness of man - The God of love life",
        "Otoboku - Maidens are Falling for Me!",
        "Prétear - The New Legend of Snow White",
        "REVAMPED - To Tame a Bad Boy (Short Film 2021)",
        "RIN - Daughters of Mnemosyne",
        "Romeo e Giulietta - Ama e Cambia il Mondo",
        "SCP - Containment Breach",
        "Saint Seiya: Episode G - Assassin",
        "Saint Seiya: Next Dimension - Myth of Hades",
        "Tatakau Shisho - The Book of Bantorra",
        "Vampire: The Masquerade - Swansong",
        "Watamote - No Matter How I Look At It It's You Guys' Fault I'm Unpopular!",
        "Who Are You - School 2015",
        "ef - a fairy tale of the two.",
    ]
}
