#!/bin/sh
# Materialise Packages/FluidAudio — the patched FluidAudio the Core ML Kokoro
# TTS engine builds against.
#
# `Packages/` is gitignored, exactly like `Vendor/` (MuPDF) and the sherpa-onnx
# fetch: a 6.4 MB third-party source tree does not belong in this repo's
# history, and a fork pinned by revision plus a reviewable patch is both
# smaller and easier to re-apply when upstream moves.
#
# Upstream is Apache-2.0 (see Packages/FluidAudio/LICENSE after running this,
# and kudos-ao3-reader/Legal/ThirdPartyNotices.txt), which is one-way
# compatible with this project's AGPL-3.0.
#
# Usage:  Scripts/fetch-fluidaudio.sh [--force]
set -eu

REPO="https://github.com/FluidInference/FluidAudio.git"
# Pinned exactly: v0.15.6. Bump both together, then re-run with --force and
# re-verify the patch still applies.
COMMIT="4dbf4f9f9a5ff3a53ade848d7ba4e3df13db859b"
VERSION="0.15.6"

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$ROOT/Packages/FluidAudio"
PATCH="$ROOT/Scripts/fluidaudio-kudos.patch"

if [ "${1:-}" = "--force" ]; then
  rm -rf "$DEST"
elif [ -d "$DEST" ]; then
  echo "Packages/FluidAudio already present. Re-run with --force to replace it."
  exit 0
fi

[ -f "$PATCH" ] || { echo "missing $PATCH" >&2; exit 1; }

WORKDIR="$(mktemp -d "${TMPDIR:-/tmp}/fluidaudio.XXXXXX")"
cleanup() { rm -rf "$WORKDIR"; }
trap cleanup EXIT

echo "Cloning FluidAudio $VERSION ($COMMIT)…"
git clone -q --filter=blob:none "$REPO" "$WORKDIR/FluidAudio"
git -C "$WORKDIR/FluidAudio" checkout -q "$COMMIT"

ACTUAL="$(git -C "$WORKDIR/FluidAudio" rev-parse HEAD)"
if [ "$ACTUAL" != "$COMMIT" ]; then
  echo "commit mismatch: wanted $COMMIT, got $ACTUAL" >&2
  exit 1
fi
rm -rf "$WORKDIR/FluidAudio/.git"

# Kudos links the FluidAudio library only. The CLI executable and the upstream
# test target are dropped (the Package.swift hunk in the patch removes their
# declarations, so their sources must go too), along with the benchmark note
# the upstream manifest `exclude:`s.
rm -rf "$WORKDIR/FluidAudio/Sources/FluidAudioCLI"
rm -rf "$WORKDIR/FluidAudio/Tests"
rm -f  "$WORKDIR/FluidAudio/Sources/FluidAudio/ASR/Parakeet/Unified/benchmark.md"
rm -f  "$WORKDIR/FluidAudio/Sources/FastClusterWrapper/README.md"

echo "Applying Scripts/fluidaudio-kudos.patch…"
git -C "$WORKDIR/FluidAudio" apply --verbose "$PATCH"

mkdir -p "$ROOT/Packages"
mv "$WORKDIR/FluidAudio" "$DEST"

cat > "$DEST/KUDOS_PATCHES.md" <<EOF
# Kudos patches on FluidAudio $VERSION

Generated by \`Scripts/fetch-fluidaudio.sh\` — **do not edit this tree by
hand.** Change \`Scripts/fluidaudio-kudos.patch\` instead and re-run with
\`--force\`, so the divergence stays reviewable and re-appliable.

Pinned at upstream commit \`$COMMIT\`.

1. **Package.swift** — drop the \`fluidaudiocli\` executable product, the
   \`FluidAudioCLI\` target, and the upstream test target. Kudos links the
   library only; building a CLI into an iOS app target is pointless and the
   test target drags in resources the app does not ship.
2. **G2P** (\`G2PModel.swift\`) — load encoder/decoder \`.cpuAndGPU\` instead
   of \`.cpuOnly\`. \`cpuOnly\` *is* BNNS, and fanfic OOV words run a 64-step
   BART decode with a new shape every step.
3. **Seven-stage load** (\`KokoroAneModelStore.swift\`) — \`reshapeFrequency =
   .infrequent\` and \`specializationStrategy = .fastPrediction\`, so flexible
   \`[1, T]\` inputs do not rebuild a graph per utterance length.
4. **Seven-stage predict** (\`KokoroAneSynthesizer.swift\`) — synchronous
   \`MLModel.prediction(from:)\` instead of \`await\`. The async API hops to
   \`com.apple.e5rt.concurrentExecutionQueue\`, the faulting queue in every
   Kudos crash log.
5. **English frontend** (\`KokoroAneEnglishPhonemizer.swift\`) — after a
   complete lexicon miss and before letter-name initialisms, try apostrophe
   reinsertion (\`dont\` → \`don't\`) and de-elongation (\`yesss\` → \`yes\`).
   \`cant\` / \`beer\` never reach these because they hit the lexicon first.
6. **English \`the\`/\`to\` sandhi** (\`KokoroAneEnglishPhonemizer.swift\`) —
   after every word is resolved, rewrite \`the\`/\`The\` and \`to\`/\`To\`
   from the following phoneme (Misaki \`future_vowel\`). The bundled lexicon
   stores only the strong form (\`ði\`, \`tu\`), so "the book" otherwise
   says "thee book" — 105,383 + 67,403 corpus hits, about 7% of every
   word. All-caps \`THE\`/\`TO\` are left alone (POS-gated in Misaki).
7. **English possessive \`X's\`** (\`KokoroAneEnglishPhonemizer.swift\`) —
   after a complete lexicon miss, if the token is \`X's\` and \`X\` is a
   lexicon hit, append Misaki's \`_s\` allomorph (\`ptkfθ\` → \`s\`,
   sibilants → \`ᵻz\`, else \`z\`). Gated on the stem already being
   known: G2P on the whole token already applies the clitic. \`James'\`
   (apostrophe, no \`s\`) is out of scope. The real lexicon has not one
   possessive while every base is present; 5,896 corpus hits, ~37%
   coverage when the base is known.

Patches 2–4 exist to route around the iOS 26.x libBNNS \`SIGSEGV\`
(FluidAudio #817 / #844). Kudos additionally does not run the Core ML engine
at all on iOS 26 — see \`KokoroAnePlayback\`. Patch 5 is a fanfic-frontend
recovery; patch 6 is the Misaki \`the\`/\`to\` weak-form post-pass; patch 7
is possessive allomorph derivation. None of 5–7 change compute-unit routing.
EOF

echo "FluidAudio $VERSION ready at Packages/FluidAudio"
